name: CI

on:
  push:
  
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Upload extension
        uses: actions/upload-artifact@v2.3.1
        with:
          path: extension
